#!/usr/bin/env bash
# NOTE: this script should be called from the parent directory to
# properly work

SCRIPT_DIR=$(dirname $0);
URL=${1:-http://localhost:9090}

echo "Preparing bundle for types from $URL"

set -ex

corepack enable;
corepack install;

# Ensure clean working directory
rm -rf dist;
rm -rf node_modules;
rm -rf packages/server/dist;
rm -rf packages/server/node_modules;

pushd $SCRIPT_DIR;
set +e
./build-types $URL;
set -e
popd

pnpm -r --filter "!mcp-plugin" install;
pnpm -r --filter "mcp-server" run build;

rsync -avr packages/server/dist/ ./dist/;

cp packages/server/package.json ./dist/;
cp pnpm-lock.yaml ./dist/;

touch ./dist/pnpm-workspace.yaml;

node <<'EOF'
const fs = require("fs");
const path = "./dist/package.json";
const pkg = JSON.parse(fs.readFileSync(path, "utf8"));

if (pkg.dependencies) {
  delete pkg.dependencies["penpot-mcp"];
}

delete pkg.devDependencies;
delete pkg["ts-node"];

fs.writeFileSync(path, `${JSON.stringify(pkg, null, 2)}\n`);
EOF

pushd ./dist;
pnpm install --prod --lockfile-only --no-frozen-lockfile;
popd;

cat <<EOF | tee ./dist/setup
#!/usr/bin/env bash
set -e;
corepack enable;
corepack install;
pnpm install --prod --frozen-lockfile
EOF

chmod +x ./dist/setup;
